# Generated by Django 2.2 on 2019-11-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_billing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='payment_option',
        ),
    ]
